  0%|          | 0/24393 [00:00<?, ?it/s]  0%|          | 1/24393 [00:04<27:24:17,  4.04s/it]  0%|          | 2/24393 [00:05<17:00:36,  2.51s/it]  0%|          | 4/24393 [00:08<13:39:59,  2.02s/it]  0%|          | 5/24393 [00:09<10:41:36,  1.58s/it]  0%|          | 6/24393 [00:10<9:50:52,  1.45s/it]   0%|          | 8/24393 [00:13<9:23:24,  1.39s/it]  0%|          | 9/24393 [00:13<7:26:51,  1.10s/it]  0%|          | 10/24393 [00:14<6:59:31,  1.03s/it]  0%|          | 11/24393 [00:14<5:38:20,  1.20it/s]  0%|          | 13/24393 [00:15<4:00:54,  1.69it/s]  0%|          | 14/24393 [00:15<3:58:11,  1.71it/s]  0%|          | 16/24393 [00:16<3:43:17,  1.82it/s]  0%|          | 17/24393 [00:16<3:05:07,  2.19it/s]  0%|          | 18/24393 [00:17<3:00:30,  2.25it/s]  0%|          | 19/24393 [00:17<2:41:55,  2.51it/s]  0%|          | 20/24393 [00:17<2:35:48,  2.61it/s]  0%|          | 21/24393 [00:18<2:38:46,  2.56it/s]  0%|          | 22/24393 [00:18<2:10:34,  3.11it/s]  0%|          | 23/24393 [00:19<2:44:19,  2.47it/s]  0%|          | 24/24393 [00:19<2:30:15,  2.70it/s]  0%|          | 25/24393 [00:19<2:33:30,  2.65it/s]  0%|          | 28/24393 [00:20<2:29:24,  2.72it/s]  0%|          | 29/24393 [00:21<2:38:16,  2.57it/s]  0%|          | 30/24393 [00:22<3:40:49,  1.84it/s]  0%|          | 31/24393 [00:23<4:37:13,  1.46it/s]  0%|          | 32/24393 [00:24<5:38:57,  1.20it/s]  0%|          | 33/24393 [00:26<6:28:45,  1.04it/s]  0%|          | 34/24393 [00:27<6:28:56,  1.04it/s]  0%|          | 35/24393 [00:27<5:47:45,  1.17it/s]  0%|          | 36/24393 [00:27<4:23:31,  1.54it/s]  0%|          | 37/24393 [00:28<5:05:56,  1.33it/s]  0%|          | 40/24393 [00:29<3:04:41,  2.20it/s]  0%|          | 41/24393 [00:30<3:17:55,  2.05it/s]  0%|          | 42/24393 [00:30<3:22:42,  2.00it/s]  0%|          | 43/24393 [00:31<3:14:39,  2.08it/s]  0%|          | 44/24393 [00:31<3:07:44,  2.16it/s]  0%|          | 46/24393 [00:31<2:23:41,  2.82it/s]  0%|          | 47/24393 [00:32<3:27:33,  1.95it/s]  0%|          | 48/24393 [00:33<3:03:58,  2.21it/s]  0%|          | 49/24393 [00:34<4:11:07,  1.62it/s]  0%|          | 50/24393 [00:34<4:10:33,  1.62it/s]  0%|          | 51/24393 [00:36<5:50:58,  1.16it/s]  0%|          | 52/24393 [00:36<4:54:23,  1.38it/s]  0%|          | 53/24393 [00:37<4:28:09,  1.51it/s]  0%|          | 54/24393 [00:37<4:11:02,  1.62it/s]  0%|          | 55/24393 [00:38<4:13:21,  1.60it/s]  0%|          | 57/24393 [00:39<4:08:32,  1.63it/s]  0%|          | 58/24393 [00:39<3:20:28,  2.02it/s]  0%|          | 59/24393 [00:41<5:17:48,  1.28it/s]  0%|          | 61/24393 [00:42<4:10:09,  1.62it/s]  0%|          | 62/24393 [00:42<4:03:01,  1.67it/s]  0%|          | 63/24393 [00:42<3:21:52,  2.01it/s]  0%|          | 64/24393 [00:43<3:10:46,  2.13it/s]  0%|          | 65/24393 [00:43<3:27:32,  1.95it/s]  0%|          | 66/24393 [00:44<3:10:44,  2.13it/s]  0%|          | 67/24393 [00:44<2:38:04,  2.56it/s]  0%|          | 68/24393 [00:44<2:04:21,  3.26it/s]  0%|          | 69/24393 [00:44<2:18:56,  2.92it/s]  0%|          | 70/24393 [00:45<2:49:02,  2.40it/s]  0%|          | 71/24393 [00:46<3:16:31,  2.06it/s]  0%|          | 72/24393 [00:47<4:27:05,  1.52it/s]  0%|          | 73/24393 [00:47<4:27:36,  1.51it/s]  0%|          | 75/24393 [00:48<2:44:31,  2.46it/s]  0%|          | 76/24393 [00:50<5:40:20,  1.19it/s]  0%|          | 78/24393 [00:51<4:18:29,  1.57it/s]  0%|          | 79/24393 [00:51<3:53:19,  1.74it/s]  0%|          | 80/24393 [00:52<4:53:57,  1.38it/s]  0%|          | 81/24393 [00:52<4:19:27,  1.56it/s]  0%|          | 82/24393 [00:53<5:02:20,  1.34it/s]  0%|          | 83/24393 [00:54<5:07:32,  1.32it/s]  0%|          | 84/24393 [00:55<4:59:24,  1.35it/s]  0%|          | 85/24393 [00:55<4:23:18,  1.54it/s]  0%|          | 88/24393 [00:58<5:24:44,  1.25it/s]  0%|          | 89/24393 [00:58<4:32:52,  1.48it/s]  0%|          | 90/24393 [00:59<4:45:39,  1.42it/s]  0%|          | 91/24393 [00:59<3:48:11,  1.77it/s]  0%|          | 92/24393 [01:00<4:05:22,  1.65it/s]  0%|          | 93/24393 [01:02<5:55:10,  1.14it/s]  0%|          | 94/24393 [01:02<4:56:07,  1.37it/s]  0%|          | 95/24393 [01:03<4:34:19,  1.48it/s]  0%|          | 96/24393 [01:03<4:01:04,  1.68it/s]  0%|          | 97/24393 [01:03<3:37:48,  1.86it/s]  0%|          | 99/24393 [01:04<2:36:57,  2.58it/s]  0%|          | 100/24393 [01:05<3:18:27,  2.04it/s]  0%|          | 102/24393 [01:05<2:20:14,  2.89it/s]  0%|          | 103/24393 [01:06<3:48:03,  1.78it/s]  0%|          | 106/24393 [01:06<2:12:22,  3.06it/s]  0%|          | 107/24393 [01:07<2:10:26,  3.10it/s]  0%|          | 108/24393 [01:08<3:40:28,  1.84it/s]  0%|          | 109/24393 [01:09<3:37:32,  1.86it/s]  0%|          | 110/24393 [01:09<3:29:43,  1.93it/s]  0%|          | 111/24393 [01:09<3:06:21,  2.17it/s]  0%|          | 112/24393 [01:10<2:54:50,  2.31it/s]  0%|          | 113/24393 [01:10<2:57:40,  2.28it/s]  0%|          | 115/24393 [01:11<2:19:32,  2.90it/s]  0%|          | 116/24393 [01:15<9:09:56,  1.36s/it]  0%|          | 117/24393 [01:17<9:21:10,  1.39s/it]  0%|          | 118/24393 [01:17<7:50:47,  1.16s/it]  0%|          | 119/24393 [01:17<5:54:27,  1.14it/s]  0%|          | 120/24393 [01:18<5:02:04,  1.34it/s]  0%|          | 121/24393 [01:19<5:13:41,  1.29it/s]  1%|          | 122/24393 [01:19<4:21:39,  1.55it/s]  1%|          | 123/24393 [01:19<4:03:48,  1.66it/s]  1%|          | 124/24393 [01:20<3:58:57,  1.69it/s]  1%|          | 125/24393 [01:20<3:48:25,  1.77it/s]  1%|          | 126/24393 [01:21<3:30:01,  1.93it/s]  1%|          | 127/24393 [01:21<3:01:27,  2.23it/s]  1%|          | 128/24393 [01:21<2:47:06,  2.42it/s]  1%|          | 129/24393 [01:22<3:00:51,  2.24it/s]  1%|          | 130/24393 [01:24<5:32:31,  1.22it/s]  1%|          | 131/24393 [01:24<4:57:25,  1.36it/s]  1%|          | 132/24393 [01:25<4:40:39,  1.44it/s]  1%|          | 133/24393 [01:26<4:42:16,  1.43it/s]  1%|          | 134/24393 [01:26<3:45:28,  1.79it/s]  1%|          | 136/24393 [01:26<2:17:09,  2.95it/s]  1%|          | 137/24393 [01:27<3:03:01,  2.21it/s]  1%|          | 138/24393 [01:27<3:14:26,  2.08it/s]  1%|          | 139/24393 [01:27<2:35:05,  2.61it/s]  1%|          | 140/24393 [01:28<3:40:46,  1.83it/s]  1%|          | 141/24393 [01:30<4:56:48,  1.36it/s]  1%|          | 143/24393 [01:31<5:02:31,  1.34it/s]  1%|          | 144/24393 [01:31<4:14:45,  1.59it/s]  1%|          | 145/24393 [01:32<3:23:48,  1.98it/s]  1%|          | 147/24393 [01:32<2:23:53,  2.81it/s]  1%|          | 148/24393 [01:32<2:16:21,  2.96it/s]  1%|          | 149/24393 [01:32<2:17:02,  2.95it/s]  1%|          | 151/24393 [01:34<2:52:01,  2.35it/s]  1%|          | 152/24393 [01:34<3:28:12,  1.94it/s]  1%|          | 153/24393 [01:36<4:59:37,  1.35it/s]  1%|          | 154/24393 [01:36<4:03:15,  1.66it/s]  1%|          | 155/24393 [01:36<3:21:34,  2.00it/s]  1%|          | 156/24393 [01:38<5:37:56,  1.20it/s]  1%|          | 158/24393 [01:39<4:01:33,  1.67it/s]  1%|          | 160/24393 [01:39<2:40:41,  2.51it/s]  1%|          | 161/24393 [01:39<2:27:35,  2.74it/s]  1%|          | 162/24393 [01:39<2:06:58,  3.18it/s]  1%|          | 163/24393 [01:39<1:52:23,  3.59it/s]  1%|          | 164/24393 [01:40<2:08:20,  3.15it/s]  1%|          | 166/24393 [01:41<3:05:17,  2.18it/s]  1%|          | 167/24393 [01:41<2:33:29,  2.63it/s]  1%|          | 168/24393 [01:41<2:23:52,  2.81it/s]  1%|          | 169/24393 [01:42<2:05:55,  3.21it/s]  1%|          | 171/24393 [01:43<3:43:58,  1.80it/s]  1%|          | 172/24393 [01:44<4:16:06,  1.58it/s]  1%|          | 173/24393 [01:45<3:46:11,  1.78it/s]  1%|          | 174/24393 [01:45<3:28:00,  1.94it/s]  1%|          | 175/24393 [01:45<3:06:38,  2.16it/s]  1%|          | 176/24393 [01:46<4:03:01,  1.66it/s]  1%|          | 177/24393 [01:46<3:18:03,  2.04it/s]  1%|          | 178/24393 [01:47<3:23:28,  1.98it/s]  1%|          | 179/24393 [01:48<3:50:08,  1.75it/s]  1%|          | 180/24393 [01:48<3:09:05,  2.13it/s]  1%|          | 181/24393 [01:48<2:37:41,  2.56it/s]  1%|          | 182/24393 [01:49<3:23:55,  1.98it/s]  1%|          | 183/24393 [01:49<3:15:48,  2.06it/s]  1%|          | 184/24393 [01:51<4:50:32,  1.39it/s]  1%|          | 185/24393 [01:51<4:34:34,  1.47it/s]  1%|          | 186/24393 [01:52<5:14:28,  1.28it/s]  1%|          | 187/24393 [01:52<3:57:45,  1.70it/s]  1%|          | 188/24393 [01:53<4:46:57,  1.41it/s]  1%|          | 189/24393 [01:54<3:37:58,  1.85it/s]  1%|          | 190/24393 [01:55<4:38:59,  1.45it/s]  1%|          | 191/24393 [01:56<5:14:59,  1.28it/s]  1%|          | 192/24393 [01:56<4:27:52,  1.51it/s]  1%|          | 193/24393 [01:57<5:48:52,  1.16it/s]  1%|          | 194/24393 [01:57<4:32:10,  1.48it/s]  1%|          | 196/24393 [01:58<2:44:08,  2.46it/s]  1%|          | 197/24393 [01:59<3:40:50,  1.83it/s]  1%|          | 198/24393 [02:00<5:44:50,  1.17it/s]  1%|          | 199/24393 [02:01<4:27:22,  1.51it/s]  1%|          | 200/24393 [02:01<4:31:30,  1.49it/s]  1%|          | 202/24393 [02:02<3:22:59,  1.99it/s]  1%|          | 204/24393 [02:02<2:29:17,  2.70it/s]  1%|          | 205/24393 [02:04<4:41:51,  1.43it/s]  1%|          | 206/24393 [02:04<3:46:47,  1.78it/s]  1%|          | 207/24393 [02:04<3:14:51,  2.07it/s]  1%|          | 208/24393 [02:05<2:57:37,  2.27it/s]  1%|          | 210/24393 [02:05<2:34:47,  2.60it/s]  1%|          | 211/24393 [02:06<2:50:58,  2.36it/s]  1%|          | 212/24393 [02:06<2:18:40,  2.91it/s]  1%|          | 213/24393 [02:07<4:01:12,  1.67it/s]  1%|          | 214/24393 [02:09<6:12:17,  1.08it/s]  1%|          | 215/24393 [02:10<7:00:04,  1.04s/it]  1%|          | 216/24393 [02:11<5:24:41,  1.24it/s]  1%|          | 217/24393 [02:11<4:35:22,  1.46it/s]  1%|          | 218/24393 [02:12<5:12:35,  1.29it/s]  1%|          | 220/24393 [02:12<3:21:17,  2.00it/s]  1%|          | 221/24393 [02:12<2:44:14,  2.45it/s]  1%|          | 222/24393 [02:14<4:06:56,  1.63it/s]  1%|          | 223/24393 [02:14<3:22:35,  1.99it/s]  1%|          | 224/24393 [02:15<4:49:49,  1.39it/s]  1%|          | 225/24393 [02:15<3:39:07,  1.84it/s]  1%|          | 226/24393 [02:17<6:33:59,  1.02it/s]  1%|          | 227/24393 [02:18<5:41:47,  1.18it/s]  1%|          | 228/24393 [02:19<5:40:38,  1.18it/s]  1%|          | 229/24393 [02:19<4:29:14,  1.50it/s]  1%|          | 230/24393 [02:19<3:35:33,  1.87it/s]  1%|          | 231/24393 [02:21<5:11:21,  1.29it/s]  1%|          | 232/24393 [02:21<4:17:48,  1.56it/s]  1%|          | 233/24393 [02:21<3:26:03,  1.95it/s]  1%|          | 234/24393 [02:21<3:03:14,  2.20it/s]  1%|          | 235/24393 [02:21<2:22:26,  2.83it/s]  1%|          | 236/24393 [02:23<3:53:18,  1.73it/s]  1%|          | 237/24393 [02:23<3:52:41,  1.73it/s]  1%|          | 240/24393 [02:23<2:02:48,  3.28it/s]  1%|          | 241/24393 [02:24<1:46:54,  3.77it/s]  1%|          | 242/24393 [02:25<3:31:37,  1.90it/s]  1%|          | 243/24393 [02:25<3:04:49,  2.18it/s]Process ForkPoolWorker-17:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-10:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-3:
Traceback (most recent call last):
Process ForkPoolWorker-18:
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-16:
Process ForkPoolWorker-26:
Traceback (most recent call last):
Process ForkPoolWorker-21:
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
BrokenPipeError: [Errno 32] Broken pipe
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)

During handling of the above exception, another exception occurred:

  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
Traceback (most recent call last):
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
BrokenPipeError: [Errno 32] Broken pipe
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-9:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-28:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-4:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-27:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-7:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-24:
Traceback (most recent call last):
Process ForkPoolWorker-6:
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-1:
Traceback (most recent call last):
Process ForkPoolWorker-12:
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-13:
Traceback (most recent call last):
Process ForkPoolWorker-30:
Process ForkPoolWorker-11:
Process ForkPoolWorker-29:
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))

During handling of the above exception, another exception occurred:

  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)

During handling of the above exception, another exception occurred:

BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
BrokenPipeError: [Errno 32] Broken pipe
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
BrokenPipeError: [Errno 32] Broken pipe
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-20:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-25:
Traceback (most recent call last):
Process ForkPoolWorker-8:
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-32:
Traceback (most recent call last):
Process ForkPoolWorker-15:
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-23:
Traceback (most recent call last):
Process ForkPoolWorker-19:
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-22:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-31:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-14:
Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/queues.py", line 371, in put
    self._writer.send_bytes(obj)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 414, in _send_bytes
    self._send(header + buf)
  File "/data/home/keminglu/local_workspace/anaconda3/envs/transformers/lib/python3.8/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
